### ISSUE TITLE
Update database with ONLY most recent/missing John's Hopkins data

### ISSUE THREAD

**Issue by edhaarmanniv** [cswanson618/Project2-Main-Repo#15]
Making it so the database is not:
* required to be built from scratch every time the scrape occurs
* filled with duplicate data

**Comment by daniela-matos** [comment]
The tables are not filling with duplicate data. The scrape gets the values from a consolidated csv file, then drop the table and add the updated table to the database.

**Comment by cswanson618** [comment]
I don't think this is an issue. I think the code that Daniela wrote addresses this.

**Comment by edhaarmanniv** [comment]
Current state the program pulls in the entire consolidated csv file. What happens when we get to day 1000 of the data? Are we going to reload an entire csv into the database every time data is refreshed? Or should we only add the most recent data/data for dates not included in db from last time of refresh?

**Comment by daniela-matos** [comment]
As we talked yesterday, in this case, it is better to drop the table and create a new table.
